before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq grass grass-dev python-gdal

env:
 - GISBASE=/usr/lib/grass64
 - LD_LIBRARY_PATH=/usr/lib/grass64/lib

script: "python -m unittest discover -v"

